Ext.define('Документы.ОтпускПоУходуЗаРебенком.ФормаВыбора',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:660px;height:421px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Отпуска по уходу за ребенком',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:644px;height:380px;',
			height: 380,width: 644,
			columns:
			[
				{
					text:'',
					width:'32',
				},
				{
					text:'Дата',
					width:'132',
				},
				{
					text:'Номер',
					width:'80',
				},
				{
					text:'Организация',
					width:'120',
				},
				{
					text:'Сотрудник',
					width:'120',
				},
				{
					text:'Дата начала',
					width:'80',
				},
				{
					text:'Дата окончания',
					width:'80',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:660px;height:25px;',
			items:
			[
				{
					text:'Действие4',
				},
				{
					text:'Действие1',
				},
				'-',
				{
					text:'Действие3',
				},
				{
					text:'Действие11',
				},
				{
					text:'',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие6',
				},
				{
					text:'',
				},
				{
					text:'Действие11',
				},
				{
					text:'Структура подчиненности документа',
				},
				'-',
				{
					text:'Действие4',
				},
				'-',
				{
					text:'Действие',
				},
				'-',
				{
					text:'',
				},
				'-',
				'-',
				{
					text:'Действие13',
				},
				'-',
				{
					text:'',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие10',
				},
				'-',
				{
					text:'Действие5',
				},
				{
					text:'Действие5',
				},
				'-',
				{
					text:'Действие',
				},
				{
					text:'Действие6',
				},
				'-',
				{
					text:'Действие7',
				},
				{
					text:'Действие2',
				},
				{
					text:'Движения документа по регистрам',
				},
				'-',
				'-',
				{
					text:'Действие14',
				},
				'-',
				{
					text:'Действие1',
				},
				{
					text:'Действие8',
				},
				'-',
				'-',
				{
					text:'',
				},
				'-',
				'-',
				{
					text:'Действие9',
				},
				'-',
				{
					text:'Действие9',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие12',
				},
			]
		},
	]
});