Ext.define('Обработки.ФормированиеЗаказовНаОбслуживаниеОС.Форма',
	{
	extend: 'Ext.window.Window',
	height: 391,width: 736,
	iconCls: 'bogus',
	title: 'Формирование заказов на обслуживание ОС',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:736px;height:25px;',
			items:
			[
				{
					text:'Заполнить',
				},
				{
					text:'Заполнить',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Подменю',
				},
				{
					text:'ОткрытьСписокЗаказовНаОбслуживаниеОС',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:366px;width:736px;height:25px;',
			items:
			[
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:227px;top:57px;width:501px;height:301px;',
			height: 301,width: 501,
			columns:
			[
				{
					text:'Использование',
				},
				{
					text:'ОсновноеСредство',
				},
				{
					text:'НоваяДатаРемонта',
				},
				{
					text:'НоваяРасчетнаяДатаРемонта',
				},
				{
					text:'КоличествоУслугиПоНормативу',
				},
				{
					text:'ПоследняяДатаРемонта',
				},
				{
					text:'Норматив',
				},
				{
					text:'ПериодичностьОбслуживанияПоНормативуПредставление',
				},
				{
					text:'ПараметрНаработкиОСПоНормативу',
				},
				{
					text:'ЗначениеПараметраНаработкиОСПоНормативуПредставление',
				},
				{
					text:'ЗначениеПараметраНаработкиОСПредставление',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:57px;width:215px;height:301px;',
			height: 301,width: 215,
			columns:
			[
				{
					text:'УслугаДата',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:227px;top:33px;width:501px;height:24px;',
			items:
			[
				{
					text:'АнализВыработкиОСПоТекущемуПараметру',
				},
				{
					text:'Действие4',
				},
				{
					text:'АнализОбслуживанияОСПоТекущейУслуге',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие3',
				},
				{
					text:'АнализВыработкиОС',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие7',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие2',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие5',
				},
				{
					text:'АнализОбслуживанияОС',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действия',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие9',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие7',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие6',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:8px;top:33px;width:215px;height:24px;',
			items:
			[
				{
					text:'НоваяДата',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие',
				},
			]
		},
	]
});