Ext.define('Обработки.ДокументооборотСКонтролирующимиОрганами.Документ_ТранспортноеСообщение_ФормаДокумента',
	{
	extend: 'Ext.window.Window',
	height: 366,width: 582,
	iconCls: 'bogus',
	title: '',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:582px;height:25px;',
			items:
			[
				{
					text:'Разделитель4',
				},
				{
					text:'РазделительЗашифровать',
				},
				{
					text:'Отправить',
				},
				{
					text:'СодержимоеТранспортныхКонтейнеров',
				},
				{
					text:'Действие',
				},
				{
					text:'Вложения',
				},
				{
					text:'РазделительОтправить',
				},
				{
					text:'Действие3',
				},
				{
					text:'РазделительПослеОбновить',
				},
				{
					text:'РазделительЗашифровать',
				},
				{
					text:'РазделительДополнительно',
				},
				{
					text:'Зашифровать',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Перечитать',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'ЦиклОбмена',
				},
				{
					text:'Зашифровать',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Перечитать',
				},
				{
					text:'Распознать',
				},
				{
					text:'Подменю',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Подменю1',
				},
				{
					text:'ДополнительныеРеквизиты',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'РазделительОтправить',
				},
				{
					text:'Выгрузить',
				},
				{
					text:'Действие5',
				},
				{
					text:'РазделительПослеОбновить',
				},
				{
					text:'Действие',
				},
				{
					text:'РазделительРаспознать',
				},
				{
					text:'ТранспортныеКонтейнеры',
				},
				{
					text:'Контейнер',
				},
				{
					text:'Отправить',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:341px;width:582px;height:25px;',
			items:
			[
				{
					text:'ОсновныеДействияФормыЗакрыть',
				},
			]
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:142px;width:566px;height:191px;',
			height: 191,width: 566,
			items:
			[
				{
					title:'ПервичноеСообщениеСодержащееОтчетность',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеОтправки',
					items:
					[
					]
				},
				{
					title:'ПротоколВходногоКонтроля',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеДоставки',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеНалогоплательщикаНаПодтверждениеОтправки',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеНалогоплательщикаНаПротоколПроверки',
					items:
					[
					]
				},
				{
					title:'УведомлениеОбУточнении',
					items:
					[
					]
				},
				{
					title:'Протокол2НДФЛ',
					items:
					[
					]
				},
				{
					title:'Прочее',
					items:
					[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ТекстПисьма',
			style: 'position:absolute;left:0px;top:3px;width:566px;height:168px;',
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:0px;top:171px;width:566px;height:20px;',
			height: 20,width: 566,
			items:
			[
				{
					title:'Страница1',
					items:
					[
					]
				},
			]
		},
					]
				},
				{
					title:'НеформализованноеСообщениеНО',
					items:
					[
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:0px;top:58px;width:566px;height:93px;',
			height: 93,width: 566,
			items:
			[
				{
					title:'Страница1',
					items:
					[
					]
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеНалогоплательщикаНаНеформализованноеСообщениеНО',
					items:
					[
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:0px;top:58px;width:566px;height:93px;',
			height: 93,width: 566,
			items:
			[
				{
					title:'Страница1',
					items:
					[
					]
				},
			]
		},
					]
				},
				{
					title:'НеформализованныйДокументНалогоплательщика',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеОтправкиНеформализованногоДокументаНалогоплательщика',
					items:
					[
					]
				},
				{
					title:'ПереподписанноеПодтверждениеОтправкиНеформализованногоДокументаНалогоплательщика',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеДоставкиНеформализованногоДокументаНалогоплательщика',
					items:
					[
					]
				},
				{
					title:'ЗапросИОН',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеОтправкиЗапроса',
					items:
					[
					]
				},
				{
					title:'ПротоколПроверкиЗапроса',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеДоставкиЗапроса',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеНалогоплательщикаНаПодтверждениеОтправкиЗапроса',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеНалогоплательщикаНаПротоколПроверкиЗапроса',
					items:
					[
					]
				},
				{
					title:'ОтветНаЗапросИОН',
					items:
					[
					]
				},
				{
					title:'ПодтверждениеНаОтветНаЗапросИОН',
					items:
					[
					]
				},
				{
					title:'ЗашифрованноеСообщениеВходящее',
					items:
					[
		{
			xtype: 'button',
			name: 'КнопкаРасшифроватьСообщение',
			text: 'Распаковать сообщение',
			style: 'position:absolute;left:200px;top:115px;width:164px;height:21px;',
		},
					]
				},
				{
					title:'ЗашифрованноеСообщениеИсходящее',
					items:
					[
		{
			xtype: 'button',
			name: 'КнопкаИзменитьСодержимое',
			text: 'Изменить содержимое',
			style: 'position:absolute;left:198px;top:115px;width:164px;height:21px;',
		},
					]
				},
				{
					title:'ПервичноеСообщениеСодержащееОтчетностьПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеПолученияПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПротоколПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПротоколКвитанцияПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'УведомлениеОбОшибке',
					items:
					[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ОписаниеОшибки',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
		},
					]
				},
				{
					title:'НеформализованноеВходящееПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'НеформализованноеИсходящееПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'НеформализованноеИсходящееКвитанцияПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'НеформализованноеВходящееКвитанцияПФР',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ДекларацияНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеДекларацияНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатПриемаДекларацияНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеРезультатПриемаНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатОбработкиДекларацияНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеРезультатОбработкиНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеДекларацияНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеПодтверждениеНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'Форма2НДФЛНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеФорма2НДФЛНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеФорма2НДФЛНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатПриемаФорма2НДФЛНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ОбращениеНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеОбращениеНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатПриемаОбращениеНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеОбращениеНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПисьмоНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеПисьмоНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РассылкаНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеРассылкаНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РассылкаНОИндивидуальная',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ЗапросНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеЗапросНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеЗапросНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатПриемаЗапросНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатОбработкиЗапросНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ЗаявлениеНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеЗаявлениеНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеЗаявлениеНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатПриемаЗаявлениеНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатОбработкиЗаявлениеРФНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеРезультатОбработкиРФНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеОбОтзывеЗаявлениеРФНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеРезультатОбработкиТСНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'СообщениеОбОтзывеЗаявлениеРФНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатОбработкиЗаявлениеТСНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ДокументНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:117px;',
			height: 117,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеДокументНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'РезультатПриемаДокументНП',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеРезультатПриемаНО',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПервичноеСообщениеСодержащееОтчетностьФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПодтверждениеДатыОтправкиФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеПодтверждениеДатыОтправкиФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеОПолученииОтчетностиФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПротоколВходногоКонтроляОтчетностиФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеПротоколВходногоКонтроляОтчетностиФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПисьмоВходящееФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:147px;',
			height: 147,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеПисьмоВходящееФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ПисьмоИсходящееФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
				{
					title:'ИзвещениеПисьмоИсходящееФСГС',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:0px;top:6px;width:566px;height:185px;',
			height: 185,width: 566,
			columns:
			[
				{
					text:'Тип',
				},
				{
					text:'Имя',
				},
				{
					text:'СообщениеВладелец',
				},
				{
					text:'ЭЦПСертификат',
				},
				{
					text:'ЭЦПЭтоПодписьАбонента',
				},
				{
					text:'ЭЦПСтатусПроверки',
				},
				{
					text:'ТипФайлаОтчетности',
				},
			]
		},
					]
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:372px;top:64px;width:190px;height:24px;',
			items:
			[
				{
					text:'Подписать',
				},
			]
		},
	]
});