Ext.define('Документы.НДФЛиЕСНДоходыИНалоги.ФормаДокумента',
	{
	extend: 'Ext.window.Window',
	height: 495,width: 813,
	iconCls: 'bogus',
	title: 'Корректировка учета по НДФЛ, страховым взносам и ЕСН',
	
	items:
	[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Номер',
			style: 'position:absolute;left:424px;top:33px;width:80px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Дата',
			style: 'position:absolute;left:524px;top:33px;width:120px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Организация',
			style: 'position:absolute;left:96px;top:33px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Комментарий',
			style: 'position:absolute;left:169px;top:443px;width:636px;height:19px;',
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:813px;height:25px;',
			items:
			[
				{
					text:'Подменю1',
				},
				{
					text:'ДвиженияДокументаПоРегистрам',
				},
				{
					text:'Разделитель',
				},
				{
					text:'РедактироватьКодНомер',
				},
				{
					text:'ДействиеОткрытьСвойства1',
				},
				{
					text:'Подменю',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'СтруктураПодчиненностиДокумента',
				},
				{
					text:'ДействиеОткрытьКатегории1',
				},
				{
					text:'Разделитель4',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:470px;width:813px;height:25px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие2',
				},
			]
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:84px;width:797px;height:351px;',
			height: 351,width: 797,
			items:
			[
				{
					title:'НДФЛДоходы',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:43px;width:622px;height:300px;',
			height: 300,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'Период',
				},
				{
					text:'МесяцНалоговогоПериода',
				},
				{
					text:'ПериодРегистрации',
				},
				{
					text:'КодДохода',
				},
				{
					text:'СуммаДохода',
				},
				{
					text:'КодВычета',
				},
				{
					text:'КоличествоДетей',
				},
				{
					text:'СуммаВычета',
				},
				{
					text:'СуммаНалогаИсчисленная',
				},
				{
					text:'КолонкаКодовОП',
				},
				{
					text:'КодПоОКАТО',
				},
				{
					text:'КПП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:18px;width:622px;height:24px;',
			items:
			[
				{
					text:'Действие3',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие5',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие6',
				},
			]
		},
					]
				},
				{
					title:'НДФЛ13Исчисленный',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:18px;width:622px;height:24px;',
			items:
			[
				{
					text:'Действие',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие5',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие4',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие6',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:42px;width:622px;height:117px;',
			height: 117,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'МесяцНалоговогоПериода',
				},
				{
					text:'ПериодРегистрации',
				},
				{
					text:'Налог',
				},
				{
					text:'КолонкаКодовОП',
				},
				{
					text:'КодПоОКАТО',
				},
				{
					text:'КПП',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:206px;width:622px;height:137px;',
			height: 137,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'МесяцНалоговогоПериода',
				},
				{
					text:'ПериодРегистрации',
				},
				{
					text:'КодВычета',
				},
				{
					text:'ПримененныйВычет',
				},
				{
					text:'КолонкаКодовОП',
				},
				{
					text:'КодПоОКАТО',
				},
				{
					text:'КПП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:182px;width:622px;height:24px;',
			items:
			[
				{
					text:'Действие14',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие9',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие17',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие15',
				},
			]
		},
					]
				},
				{
					title:'НДФЛУдержанный',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:18px;width:622px;height:24px;',
			items:
			[
				{
					text:'Действие5',
				},
				{
					text:'Заполнить',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие2',
				},
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие8',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:42px;width:622px;height:301px;',
			height: 301,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'МесяцНалоговогоПериода',
				},
				{
					text:'ПериодРегистрации',
				},
				{
					text:'СтавкаНалогообложения',
				},
				{
					text:'КодДохода',
				},
				{
					text:'Налог',
				},
				{
					text:'КолонкаКодовОП',
				},
				{
					text:'КодПоОКАТО',
				},
				{
					text:'КПП',
				},
			]
		},
					]
				},
				{
					title:'СтраховыеВзносы',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:42px;width:622px;height:117px;',
			height: 117,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'МесяцРасчетногоПериода',
				},
				{
					text:'ВидДохода',
				},
				{
					text:'СуммаДохода',
				},
				{
					text:'Скидка',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'ОблагаетсяПоДополнительномуТарифу',
				},
				{
					text:'ОблагаетсяВзносамиНаДоплатуКПенсииШахтерам',
				},
				{
					text:'ЯвляетсяДоходомФармацевта',
				},
				{
					text:'ЯвляетсяДоходомЧленаЭкипажаСуднаПодФлагомРФ',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:206px;width:622px;height:137px;',
			height: 137,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'МесяцРасчетногоПериода',
				},
				{
					text:'КолонкаПФР',
				},
				{
					text:'ПФРСтраховая',
				},
				{
					text:'ПФРНакопительная',
				},
				{
					text:'ПФРСтраховаяЕНВД',
				},
				{
					text:'ПФРНакопительнаяЕНВД',
				},
				{
					text:'ПФРПоДополнительномуТарифу',
				},
				{
					text:'ПФРНаДоплатуКПенсииШахтерам',
				},
				{
					text:'КолонкаФСС',
				},
				{
					text:'ФСС',
				},
				{
					text:'ФССНесчастныеСлучаи',
				},
				{
					text:'ФССЕНВД',
				},
				{
					text:'КолонкаФОМС',
				},
				{
					text:'ФФОМС',
				},
				{
					text:'ТФОМС',
				},
				{
					text:'ФФОМСЕНВД',
				},
				{
					text:'ТФОМСЕНВД',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:18px;width:622px;height:24px;',
			items:
			[
				{
					text:'Подбор',
				},
				{
					text:'Действие6',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие7',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие4',
				},
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие2',
				},
				{
					text:'Заполнить',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:182px;width:622px;height:24px;',
			items:
			[
				{
					text:'Подбор',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие6',
				},
			]
		},
					]
				},
				{
					title:'СтраницаЕСН',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:42px;width:622px;height:117px;',
			height: 117,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'МесяцНалоговогоПериода',
				},
				{
					text:'КодДоходаЕСН',
				},
				{
					text:'СуммаДохода',
				},
				{
					text:'Скидка',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:18px;width:622px;height:24px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие7',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие6',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:206px;width:622px;height:137px;',
			height: 137,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'МесяцНалоговогоПериода',
				},
				{
					text:'ФедеральныйБюджет',
				},
				{
					text:'ФСС',
				},
				{
					text:'ФФОМС',
				},
				{
					text:'ТФОМС',
				},
				{
					text:'ПФРСтраховая',
				},
				{
					text:'ПФРНакопительная',
				},
				{
					text:'ПримененнаяЛьготаФБ',
				},
				{
					text:'ПримененнаяЛьготаФСС',
				},
				{
					text:'ПримененнаяЛьготаФОМС',
				},
				{
					text:'ПФРНакопительнаяЕНВД',
				},
				{
					text:'ПФРСтраховаяЕНВД',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:182px;width:622px;height:24px;',
			items:
			[
				{
					text:'Действие7',
				},
				{
					text:'Действие8',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие4',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие3',
				},
			]
		},
					]
				},
				{
					title:'СтраховоеОбеспечение',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:42px;width:622px;height:117px;',
			height: 117,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ПериодРегистрации',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидПособияСоциальногоСтрахования',
				},
				{
					text:'УчитыватьКакНовыйСтраховойСлучай',
				},
				{
					text:'ДатаСтраховогоСлучая',
				},
				{
					text:'ОплаченныеДни',
				},
				{
					text:'СуммаВсего',
				},
				{
					text:'СуммаСверхНорм',
				},
				{
					text:'ВыплатаЗаСчетФедеральногоБюджета',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:18px;width:622px;height:24px;',
			items:
			[
				{
					text:'Разделитель2',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие7',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие5',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:182px;width:622px;height:24px;',
			items:
			[
				{
					text:'Действие7',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие8',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие6',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:206px;width:622px;height:137px;',
			height: 137,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ПериодРегистрации',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияКонец',
				},
				{
					text:'ПособиеПоУходуЗаПервымРебенком',
				},
				{
					text:'ПособиеПоУходуЗаПервымРебенкомСверхНорм',
				},
				{
					text:'ПособиеПоУходуЗаВторымРебенком',
				},
				{
					text:'ПособиеПоУходуЗаВторымРебенкомСверхНорм',
				},
				{
					text:'ВыплатаЗаСчетФедеральногоБюджета',
				},
				{
					text:'СреднийДневнойЗаработок',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
			]
		},
					]
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Ответственный',
			style: 'position:absolute;left:424px;top:57px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'НалоговыйПериод',
			style: 'position:absolute;left:182px;top:57px;width:80px;height:19px;',
		},
	]
});