Ext.define('Справочники.Территории.ФормаСписка',
	{
	extend: 'Ext.window.Window',
	height: 260,width: 472,
	iconCls: 'bogus',
	title: 'Территории',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:472px;height:25px;',
			items:
			[
				{
					text:'Действие18',
				},
				{
					text:'Разделитель7',
				},
				{
					text:'Действие14',
				},
				{
					text:'Действие17',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Действие13',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие11',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'Подменю5',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие5',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Действие10',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие9',
				},
				{
					text:'Разделитель6',
				},
				{
					text:'Подменю4',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие19',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие7',
				},
				{
					text:'РедактироватьКодНомер',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие2',
				},
				{
					text:'Подменю',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие11',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:32px;width:456px;height:220px;',
			height: 220,width: 456,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'Код',
				},
				{
					text:'Наименование',
				},
			]
		},
	]
});