Ext.define('Документы.УчетЗаработкаРаботников.ФормаСписка',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:1000px;height:421px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Учет заработка сотрудников',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:984px;height:380px;',
			height: 380,width: 984,
			columns:
			[
				{
					text:'',
					width:'32',
				},
				{
					text:'Дата',
					width:'132',
				},
				{
					text:'Номер',
					width:'80',
				},
				{
					text:'Основание',
					width:'120',
				},
				{
					text:'Сотрудники',
					width:'100',
				},
				{
					text:'Ответственный',
					width:'120',
				},
				{
					text:'Комментарий',
					width:'120',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:1000px;height:25px;',
			items:
			[
				{
					text:'Действие13',
				},
				{
					text:'Действие21',
				},
				{
					text:'',
				},
				{
					text:'Движения документа по регистрам',
				},
				'-',
				{
					text:'Действие20',
				},
				{
					text:'',
				},
				'-',
				'-',
				'-',
				{
					text:'Действие16',
				},
				{
					text:'Действие17',
				},
				'-',
				{
					text:'Действие20',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие25',
				},
				{
					text:'Действие18',
				},
				{
					text:'Действие23',
				},
				{
					text:'',
				},
				{
					text:'Действие17',
				},
				'-',
				{
					text:'Действие26',
				},
				{
					text:'',
				},
				{
					text:'Действие22',
				},
				{
					text:'Действие18',
				},
				'-',
				'-',
				{
					text:'Действие21',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие27',
				},
				{
					text:'Действие24',
				},
				{
					text:'Действие19',
				},
				'-',
				{
					text:'Действие29',
				},
				{
					text:'Структура подчиненности документа',
				},
				{
					text:'Действие19',
				},
				'-',
				'-',
				{
					text:'Действие28',
				},
				{
					text:'Действие15',
				},
				'-',
				{
					text:'Действие14',
				},
				{
					text:'Действие15',
				},
				'-',
				'-',
				{
					text:'Действие12',
				},
				'-',
			]
		},
	]
});