Ext.define('Документы.ВводПостоянногоНачисленияИлиУдержания.ФормаСписка',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:1000px;height:421px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Ввод постоянного начисления или удержания',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:984px;height:380px;',
			height: 380,width: 984,
			columns:
			[
				{
					text:'',
					width:'20',
				},
				{
					text:'Дата',
					width:'132',
				},
				{
					text:'Номер',
					width:'80',
				},
				{
					text:'Сотрудники',
					width:'100',
				},
				{
					text:'Вид расчета',
					width:'135',
				},
				{
					text:'Действие',
					width:'100',
				},
				{
					text:'Дата начала',
					width:'84',
				},
				{
					text:'Дата окончания',
					width:'84',
				},
				{
					text:'Ответственный',
					width:'120',
				},
				{
					text:'Комментарий',
					width:'100',
				},
				{
					text:'Подразделение',
					width:'100',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:1000px;height:25px;',
			items:
			[
				'-',
				'-',
				{
					text:'Действие4',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие9',
				},
				'-',
				{
					text:'Движения документа по регистрам',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие6',
				},
				{
					text:'',
				},
				'-',
				{
					text:'Действие12',
				},
				{
					text:'Действие8',
				},
				'-',
				'-',
				{
					text:'Действие6',
				},
				'-',
				'-',
				{
					text:'Действие8',
				},
				'-',
				{
					text:'Действие3',
				},
				{
					text:'Действие10',
				},
				{
					text:'Структура подчиненности документа',
				},
				'-',
				{
					text:'Действие13',
				},
				{
					text:'',
				},
				{
					text:'Действие1',
				},
				'-',
				{
					text:'Действие5',
				},
				{
					text:'Действие11',
				},
				'-',
				'-',
				{
					text:'',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие7',
				},
				{
					text:'',
				},
				'-',
				{
					text:'Действие2',
				},
				'-',
				{
					text:'Действие14',
				},
			]
		},
	]
});