Ext.define('Документы.РасчетЕСН.ФормаДокумента',
	{
	extend: 'Ext.window.Window',
	height: 432,width: 604,
	iconCls: 'bogus',
	title: 'Расчет ЕСН',
	
	items:
	[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Номер',
			style: 'position:absolute;left:96px;top:33px;width:80px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Дата',
			style: 'position:absolute;left:196px;top:33px;width:120px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ПериодРегистрации',
			style: 'position:absolute;left:441px;top:33px;width:155px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Организация',
			style: 'position:absolute;left:96px;top:57px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ПодразделениеОрганизации',
			style: 'position:absolute;left:96px;top:81px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Ответственный',
			style: 'position:absolute;left:441px;top:57px;width:155px;height:19px;',
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:604px;height:25px;',
			items:
			[
				{
					text:'Разделитель3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие4',
				},
				{
					text:'РедактироватьКодНомер',
				},
				{
					text:'ЗаполнитьИРассчитать',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие',
				},
				{
					text:'СтруктураПодчиненностиДокумента',
				},
				{
					text:'Действие5',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Действие',
				},
				{
					text:'ДвиженияДокументаПоРегистрам',
				},
				{
					text:'Подменю',
				},
				{
					text:'ОткрытьСвойства',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие6',
				},
				{
					text:'ОткрытьКатегории',
				},
				{
					text:'Разделитель6',
				},
				{
					text:'Действие7',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие2',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:407px;width:604px;height:25px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Комментарий',
			style: 'position:absolute;left:96px;top:380px;width:500px;height:19px;',
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:108px;width:588px;height:267px;',
			height: 267,width: 588,
			items:
			[
				{
					title:'Страница1',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:574px;height:24px;',
			items:
			[
				{
					text:'Действие12',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие14',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие17',
				},
				{
					text:'Действие9',
				},
				{
					text:'РассчитатьЕСН',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:574px;height:217px;',
			height: 217,width: 574,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'ФедеральныйБюджет',
				},
				{
					text:'ПримененнаяЛьготаФБ',
				},
				{
					text:'ФСС',
				},
				{
					text:'ПримененнаяЛьготаФСС',
				},
				{
					text:'ТФОМС',
				},
				{
					text:'ФФОМС',
				},
				{
					text:'ПримененнаяЛьготаФОМС',
				},
				{
					text:'ПФРНакопительная',
				},
				{
					text:'ПФРНакопительнаяЕНВД',
				},
				{
					text:'ПФРСтраховая',
				},
				{
					text:'ПФРСтраховаяЕНВД',
				},
			]
		},
					]
				},
				{
					title:'Страница2',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:574px;height:24px;',
			items:
			[
				{
					text:'Действие13',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие14',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие17',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие9',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие16',
				},
				{
					text:'Подбор',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:574px;height:217px;',
			height: 217,width: 574,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'КодДоходаЕСН',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияОкончание',
				},
				{
					text:'Результат',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
			]
		},
					]
				},
				{
					title:'Страница3',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:574px;height:24px;',
			items:
			[
				{
					text:'Действие14',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие10',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие17',
				},
				{
					text:'Действие15',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие11',
				},
				{
					text:'РассчитатьСкидку',
				},
				{
					text:'Действие16',
				},
				{
					text:'Разделитель',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:574px;height:217px;',
			height: 217,width: 574,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'КодДоходаЕСН',
				},
				{
					text:'Скидка',
				},
				{
					text:'Результат',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
			]
		},
					]
				},
				{
					title:'ПособияСоциальномуСтрахованию',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:574px;height:24px;',
			items:
			[
				{
					text:'Действие14',
				},
				{
					text:'Действие17',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие13',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие10',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:574px;height:217px;',
			height: 217,width: 574,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидПособияСоциальногоСтрахования',
				},
				{
					text:'СпособФинансированияПособий',
				},
				{
					text:'ЗаголовокСтраховогоСлучая',
				},
				{
					text:'УчитыватьКакНовыйСтраховойСлучай',
				},
				{
					text:'ДатаСтраховогоСлучая',
				},
				{
					text:'ЗаголовокПериодаОплаты',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияКонец',
				},
				{
					text:'СуммаВсего',
				},
				{
					text:'ОплаченныеДни',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'ДокументОснование',
				},
				{
					text:'Сторно',
				},
			]
		},
					]
				},
				{
					title:'ПособияПоУходуЗаРебенком',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:574px;height:24px;',
			items:
			[
				{
					text:'Действие9',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие14',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие13',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие17',
				},
				{
					text:'Действие16',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:574px;height:217px;',
			height: 217,width: 574,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияКонец',
				},
				{
					text:'СреднийДневнойЗаработок',
				},
				{
					text:'ПособиеПоУходуЗаПервымРебенком',
				},
				{
					text:'ПособиеПоУходуЗаВторымРебенком',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
			]
		},
					]
				},
			]
		},
	]
});