Ext.define('Справочники.ФизическиеЛица.ФормаВводаДанныхСЗВК',
	{
	extend: 'Ext.window.Window',
	height: 455,width: 756,
	iconCls: 'bogus',
	title: 'Ввод данных СЗВ-К',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:430px;width:756px;height:25px;',
			items:
			[
				{
					text:'Разделитель1',
				},
				{
					text:'Справка',
				},
				{
					text:'Закрыть',
				},
				{
					text:'ОК',
				},
				{
					text:'Разделитель',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:165px;width:740px;height:152px;',
			height: 152,width: 740,
			columns:
			[
				{
					text:'НевидимаяКолонка',
				},
				{
					text:'Организация',
				},
				{
					text:'ВидДеятельности',
				},
				{
					text:'НевидимаяКолонка1',
				},
				{
					text:'ДатаНачалаЗаписи',
				},
				{
					text:'ДатаОкончанияЗаписи',
				},
				{
					text:'ТерриториальныеУсловия',
				},
				{
					text:'РайонныйКоэффициент',
				},
				{
					text:'НевидимаяКолонка5',
				},
				{
					text:'ПодписьДолжности',
				},
				{
					text:'НевидимаяКолонка2',
				},
				{
					text:'НевидимаяКолонка3',
				},
				{
					text:'ОсобыеУсловияТруда',
				},
				{
					text:'ОснованиеТрудовогоСтажа',
				},
				{
					text:'НулевойПараметрТрудовогоСтажа',
				},
				{
					text:'ПервыйПараметрТрудовогоСтажа',
				},
				{
					text:'ВторойПараметрТрудовогоСтажа',
				},
				{
					text:'ТретийПараметрТрудовогоСтажа',
				},
				{
					text:'КодПозицииСписка',
				},
				{
					text:'Должность',
				},
				{
					text:'НевидимаяКолонка4',
				},
				{
					text:'ОснованиеВыслугиЛет',
				},
				{
					text:'ПервыйПараметрВыслугиЛет',
				},
				{
					text:'ВторойПараметрВыслугиЛет',
				},
				{
					text:'ТретийПараметрВыслугиЛет',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:363px;width:740px;height:60px;',
			height: 60,width: 740,
			columns:
			[
				{
					text:'ВидСтажа',
				},
				{
					text:'КодСтажа',
				},
				{
					text:'Лет',
				},
				{
					text:'Месяцев',
				},
				{
					text:'Дней',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:8px;top:339px;width:740px;height:24px;',
			items:
			[
				{
					text:'Разделитель3',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие17',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие16',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие12',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Заполнить',
				},
				{
					text:'Действие9',
				},
				{
					text:'Заполнить',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие14',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие10',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие2',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:8px;top:141px;width:740px;height:24px;',
			items:
			[
				{
					text:'Действие5',
				},
				{
					text:'ЗаполнитьПоТрудовойДеятельности',
				},
				{
					text:'Действие14',
				},
				{
					text:'Подменю',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие10',
				},
				{
					text:'ЗаполнитьПоТрудовойДеятельности1',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие17',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие15',
				},
				{
					text:'Расположить1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Расположить',
				},
				{
					text:'Действие4',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель1',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ТерриториальныеУсловияДляСЗВК',
			style: 'position:absolute;left:151px;top:8px;width:97px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'РайонныйКоэффициентДляСЗВК',
			style: 'position:absolute;left:387px;top:8px;width:52px;height:19px;',
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:50px;width:740px;height:68px;',
			height: 68,width: 740,
			columns:
			[
				{
					text:'Организация',
				},
				{
					text:'ВидДеятельности',
				},
				{
					text:'Период',
				},
			]
		},
	]
});