Ext.define('Документы.ДоговорНаВыполнениеРаботСФизЛицом.ФормаВыбора',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:676px;height:300px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Договор на выполнение работ с физ. лицом',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:660px;height:259px;',
			height: 259,width: 660,
			columns:
			[
				{
					text:'',
					width:'32',
				},
				{
					text:'Дата',
					width:'132',
				},
				{
					text:'Номер',
					width:'80',
				},
				{
					text:'Организация',
					width:'120',
				},
				{
					text:'Физическое лицо',
					width:'120',
				},
				{
					text:'Подразделение',
					width:'120',
				},
				{
					text:'Сумма за работу',
					width:'80',
				},
				{
					text:'Комментарий',
					width:'120',
				},
				{
					text:'Ответственный',
					width:'120',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:676px;height:25px;',
			items:
			[
				{
					text:'Действие8',
				},
				{
					text:'Действие4',
				},
				'-',
				{
					text:'Действие3',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие11',
				},
				'-',
				{
					text:'Действие6',
				},
				{
					text:'Действие4',
				},
				'-',
				{
					text:'',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие9',
				},
				{
					text:'Движения документа по регистрам',
				},
				{
					text:'Структура подчиненности документа',
				},
				'-',
				'-',
				{
					text:'Действие9',
				},
				'-',
				'-',
				'-',
				'-',
				{
					text:'Действие14',
				},
				{
					text:'Действие2',
				},
				{
					text:'',
				},
				'-',
				'-',
				{
					text:'Действие1',
				},
				'-',
				{
					text:'Действие6',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие11',
				},
				'-',
				'-',
				{
					text:'Действие',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие12',
				},
				'-',
				{
					text:'Действие',
				},
				{
					text:'Действие3',
				},
				{
					text:'',
				},
				{
					text:'',
				},
			]
		},
	]
});