Ext.define('Справочники.КомпетенцииРаботников.ФормаВыбора',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:512px;height:300px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Компетенции сотрудников',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:496px;height:259px;',
			height: 259,width: 496,
			columns:
			[
				{
					text:'',
					width:'32',
				},
				{
					text:'Наименование',
					width:'220',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:512px;height:25px;',
			items:
			[
				{
					text:'Действие2',
				},
				'-',
				'-',
				{
					text:'Действие9',
				},
				{
					text:'',
				},
				'-',
				'-',
				{
					text:'Действие3',
				},
				{
					text:'Действие6',
				},
				'-',
				{
					text:'Действие10',
				},
				{
					text:'Действие8',
				},
				'-',
				{
					text:'Действие7',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'',
				},
				'-',
				{
					text:'Действие8',
				},
				{
					text:'',
				},
				'-',
				{
					text:'Действие14',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие6',
				},
				'-',
				{
					text:'Действие9',
				},
				'-',
				{
					text:'Действие5',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие1',
				},
				'-',
				{
					text:'Действие7',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие15',
				},
				'-',
				{
					text:'Действие',
				},
				{
					text:'Действие',
				},
				{
					text:'Действия формы выбрать',
				},
			]
		},
	]
});