Ext.define('Документы.Сторнирование.ФормаВыбора',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:516px;height:300px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Сторнирования',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:500px;height:259px;',
			height: 259,width: 500,
			columns:
			[
				{
					text:'',
					width:'32',
				},
				{
					text:'Дата',
					width:'132',
				},
				{
					text:'Номер',
					width:'80',
				},
				{
					text:'Сторнируемый документ',
					width:'180',
				},
				{
					text:'Ответственный',
					width:'180',
				},
				{
					text:'Комментарий',
					width:'100',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:516px;height:25px;',
			items:
			[
				'-',
				{
					text:'Структура подчиненности документа',
				},
				{
					text:'Действие4',
				},
				'-',
				{
					text:'Действие7',
				},
				{
					text:'Действие',
				},
				'-',
				{
					text:'Действие10',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие14',
				},
				{
					text:'Действие10',
				},
				'-',
				{
					text:'Действие',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие11',
				},
				'-',
				'-',
				{
					text:'Действие11',
				},
				'-',
				'-',
				'-',
				'-',
				{
					text:'Действие9',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие2',
				},
				'-',
				'-',
				{
					text:'Действие8',
				},
				{
					text:'',
				},
				{
					text:'Движения документа по регистрам',
				},
				{
					text:'Действие7',
				},
				'-',
				{
					text:'Действие1',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие8',
				},
				'-',
				'-',
				{
					text:'',
				},
				{
					text:'',
				},
				'-',
				{
					text:'Действие2',
				},
			]
		},
	]
});