Ext.define('Документы.ОтчетПроизводстваЗаСмену.ФормаДокумента',
	{
	extend: 'Ext.window.Window',
	height: 421,width: 652,
	iconCls: 'bogus',
	title: 'Отчет производства за смену',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:652px;height:25px;',
			items:
			[
				{
					text:'ДействиеОткрытьКатегории1',
				},
				{
					text:'Разделитель7',
				},
				{
					text:'ПоказатьСкрытьСчетаУчета',
				},
				{
					text:'Разделитель8',
				},
				{
					text:'ДействиеОткрытьСвойства1',
				},
				{
					text:'ПроводкиДтКтНУ',
				},
				{
					text:'ДвиженияДокументаПоРегистрам',
				},
				{
					text:'Настройка',
				},
				{
					text:'Разделитель10',
				},
				{
					text:'Подменю2',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'ПроводкиДтКт',
				},
				{
					text:'ПодборПоСпецификации',
				},
				{
					text:'Разделитель',
				},
				{
					text:'СтруктураПодчиненностиДокумента',
				},
				{
					text:'Разделитель9',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:396px;width:652px;height:25px;',
			items:
			[
				{
					text:'Разделитель2',
				},
				{
					text:'Действие',
				},
				{
					text:'Печать',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель1',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Номер',
			style: 'position:absolute;left:96px;top:33px;width:80px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Дата',
			style: 'position:absolute;left:196px;top:33px;width:120px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Организация',
			style: 'position:absolute;left:96px;top:57px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Склад',
			style: 'position:absolute;left:424px;top:57px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Подразделение',
			style: 'position:absolute;left:96px;top:81px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ЗаданиеНаПроизводство',
			style: 'position:absolute;left:96px;top:105px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Комментарий',
			style: 'position:absolute;left:96px;top:369px;width:548px;height:19px;',
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:131px;width:636px;height:208px;',
			height: 208,width: 636,
			items:
			[
				{
					title:'Продукция',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:152px;',
			height: 152,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'Код',
				},
				{
					text:'Артикул',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'ХарактеристикаНоменклатуры',
				},
				{
					text:'СерияНоменклатуры',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'НаправлениеВыпуска',
				},
				{
					text:'Качество',
				},
				{
					text:'ЕдиницаМест',
				},
				{
					text:'КоэффициентМест',
				},
				{
					text:'КоличествоМест',
				},
				{
					text:'Количество',
				},
				{
					text:'Единица',
				},
				{
					text:'Коэффициент',
				},
				{
					text:'КоличествоДоделка',
				},
				{
					text:'ДоляСтоимости',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'Заказы',
				},
				{
					text:'Заказ',
				},
				{
					text:'ЗаказВыпуска',
				},
				{
					text:'ЗаказРезерв',
				},
				{
					text:'Спецификация',
				},
				{
					text:'КонечнаяПродукция',
				},
				{
					text:'Счет',
				},
				{
					text:'СчетНУ',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'СтатусПартии',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:24px;',
			items:
			[
				{
					text:'ДобавитьПоЗаказуНаПроизводство',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ЗаполнитьПоЗаказуНаПроизводство',
				},
				{
					text:'ЗаполнитьПоЗаданиюНаПроизводство',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Подбор',
				},
				{
					text:'ДобавитьИзЗаказаПокупателя',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'СерийныеНомера',
				},
				{
					text:'Получатели',
				},
				{
					text:'ПараметрыВыпуска',
				},
			]
		},
					]
				},
				{
					title:'Получатели',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:25px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'ЗаполнитьИзШаблона',
				},
				{
					text:'ПодменюЗаполнить',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:31px;width:622px;height:147px;',
			height: 147,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'ХарактеристикаНоменклатуры',
				},
				{
					text:'СерияНоменклатуры',
				},
				{
					text:'Количество',
				},
				{
					text:'Подразделение',
				},
				{
					text:'ПодразделениеОрганизации',
				},
				{
					text:'Заказ',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'ХарактерЗатрат',
				},
				{
					text:'ВидАналитики',
				},
				{
					text:'ВидАналитикиДоп',
				},
				{
					text:'ВидСубконто1',
				},
				{
					text:'ВидСубконто2',
				},
				{
					text:'ВидСубконто3',
				},
				{
					text:'ВидСубконтоНУ1',
				},
				{
					text:'ВидСубконтоНУ2',
				},
				{
					text:'ВидСубконтоНУ3',
				},
				{
					text:'Аналитика',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'Субконто1',
				},
				{
					text:'Субконто2',
				},
				{
					text:'Субконто3',
				},
				{
					text:'СубконтоНУ1',
				},
				{
					text:'СубконтоНУ2',
				},
				{
					text:'СубконтоНУ3',
				},
				{
					text:'Продукция',
				},
				{
					text:'ХарактеристикаПродукции',
				},
				{
					text:'СерияПродукции',
				},
				{
					text:'ОбъектСтроительства',
				},
				{
					text:'СпособСтроительства',
				},
				{
					text:'Проект',
				},
				{
					text:'ОтпущеноСверхЛимита',
				},
			]
		},
					]
				},
				{
					title:'Материалы',
					items:
					[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'СтатьяЗатрат',
			style: 'position:absolute;left:353px;top:6px;width:275px;height:19px;',
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:25px;width:622px;height:24px;',
			items:
			[
				{
					text:'ЗаполнитьСЗаменой',
				},
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Заполнить',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ЗаполнитьПоСпецификации',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ДобавитьИзТребованиеНакладная',
				},
				{
					text:'ЗаполнитьПоПотребностям',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:49px;width:622px;height:133px;',
			height: 133,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'Код',
				},
				{
					text:'Артикул',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'ХарактеристикаНоменклатуры',
				},
				{
					text:'СерияНоменклатуры',
				},
				{
					text:'ЕдиницаМест',
				},
				{
					text:'КоэффициентМест',
				},
				{
					text:'КоличествоМест',
				},
				{
					text:'Количество',
				},
				{
					text:'ЕдиницаИзмерения',
				},
				{
					text:'Коэффициент',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'Заказы',
				},
				{
					text:'Заказ',
				},
				{
					text:'ЗаказВыпуска',
				},
				{
					text:'Спецификация',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
					]
				},
				{
					title:'Распределение',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:152px;',
			height: 152,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'ХарактеристикаНоменклатуры',
				},
				{
					text:'СерияНоменклатуры',
				},
				{
					text:'ЕдиницаИзмерения',
				},
				{
					text:'Коэффициент',
				},
				{
					text:'Количество',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'НоменклатурнаяГруппаНЗП',
				},
				{
					text:'ЗаказНЗП',
				},
				{
					text:'Продукция',
				},
				{
					text:'ХарактеристикаПродукции',
				},
				{
					text:'СерияПродукции',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'Заказы',
				},
				{
					text:'Заказ',
				},
				{
					text:'ЗаказВыпуска',
				},
				{
					text:'Спецификация',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:24px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'Подбор',
				},
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'ДействиеЗаполнить',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ЗаполнитьПоПотребностям',
				},
			]
		},
					]
				},
				{
					title:'ТехнологическиеОперации',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:152px;',
			height: 152,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТехнологическаяОперация',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'Расценка',
				},
				{
					text:'Валюта',
				},
				{
					text:'Количество',
				},
				{
					text:'СуммаВВалютеРасценки',
				},
				{
					text:'Сумма',
				},
				{
					text:'СуммаРегл',
				},
				{
					text:'Заказ',
				},
				{
					text:'ВидАналитики',
				},
				{
					text:'ВидАналитикиДоп',
				},
				{
					text:'Аналитика',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'НоменклатурнаяГруппаДоп',
				},
				{
					text:'Продукция',
				},
				{
					text:'ХарактеристикаПродукции',
				},
				{
					text:'СерияПродукции',
				},
				{
					text:'ОбъектСтроительства',
				},
				{
					text:'СпособСтроительства',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'Проект',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:24px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'Заполнить',
				},
				{
					text:'ПодменюЗаполнить',
				},
			]
		},
					]
				},
				{
					title:'Исполнители',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:67px;width:622px;height:115px;',
			height: 115,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'КТУ',
				},
				{
					text:'СуммаКНачислению',
				},
				{
					text:'СуммаКНачислениюРегл',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:42px;width:622px;height:24px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'Рассчитать',
				},
			]
		},
					]
				},
				{
					title:'РаспределениеТехнологическихОпераций',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:150px;',
			height: 150,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТехнологическаяОперация',
				},
				{
					text:'Сумма',
				},
				{
					text:'СуммаРегл',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'Заказ',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'ХарактеристикаНоменклатуры',
				},
				{
					text:'СерияНоменклатуры',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'Спецификация',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:24px;',
			items:
			[
				{
					text:'Заполнить',
				},
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'Разделитель',
				},
			]
		},
					]
				},
				{
					title:'ПрочиеЗатраты',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:152px;',
			height: 152,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'СпособРаспределенияЗатратНаВыпуск',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'Заказ',
				},
				{
					text:'Сумма',
				},
				{
					text:'СуммаРегл',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:24px;',
			items:
			[
				{
					text:'Заполнить',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Подбор',
				},
				{
					text:'ПодменюЗаполнить',
				},
			]
		},
					]
				},
				{
					title:'РаспределениеПрочихЗатрат',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:152px;',
			height: 152,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'СпособРаспределенияЗатратНаВыпуск',
				},
				{
					text:'НоменклатурнаяГруппаНЗП',
				},
				{
					text:'ЗаказНЗП',
				},
				{
					text:'Продукция',
				},
				{
					text:'ХарактеристикаПродукции',
				},
				{
					text:'СерияПродукции',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'Заказ',
				},
				{
					text:'Спецификация',
				},
				{
					text:'Сумма',
				},
				{
					text:'СуммаРегл',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:24px;',
			items:
			[
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'ДействиеЗаполнить',
				},
				{
					text:'Действие9',
				},
			]
		},
					]
				},
				{
					title:'ВозвратныеОтходы',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:152px;',
			height: 152,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'Код',
				},
				{
					text:'Артикул',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'ХарактеристикаНоменклатуры',
				},
				{
					text:'СерияНоменклатуры',
				},
				{
					text:'ЕдиницаМест',
				},
				{
					text:'КоэффициентМест',
				},
				{
					text:'КоличествоМест',
				},
				{
					text:'Количество',
				},
				{
					text:'ЕдиницаИзмерения',
				},
				{
					text:'Коэффициент',
				},
				{
					text:'Цена',
				},
				{
					text:'Сумма',
				},
				{
					text:'СуммаРегл',
				},
				{
					text:'Спецификация',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'Заказы',
				},
				{
					text:'Заказ',
				},
				{
					text:'ЗаказРезерв',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'Счет',
				},
				{
					text:'СчетНУ',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'СтатусПартии',
				},
				{
					text:'ОтражениеВУСН',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:337px;height:24px;',
			items:
			[
				{
					text:'ЗаполнитьПоСпецификации',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Подбор',
				},
				{
					text:'ПодменюЗаполнить',
				},
				{
					text:'Разделитель1',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'СкладОтходов',
			style: 'position:absolute;left:386px;top:8px;width:242px;height:19px;',
		},
					]
				},
				{
					title:'РаспределениеВозвратныхОтходов',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:622px;height:152px;',
			height: 152,width: 622,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'ХарактеристикаНоменклатуры',
				},
				{
					text:'СерияНоменклатуры',
				},
				{
					text:'Количество',
				},
				{
					text:'ЕдиницаИзмерения',
				},
				{
					text:'Коэффициент',
				},
				{
					text:'Продукция',
				},
				{
					text:'ХарактеристикаПродукции',
				},
				{
					text:'СерияПродукции',
				},
				{
					text:'ВидВыпуска',
				},
				{
					text:'НоменклатурнаяГруппаНЗП',
				},
				{
					text:'ЗаказНЗП',
				},
				{
					text:'Заказ',
				},
				{
					text:'НоменклатурнаяГруппа',
				},
				{
					text:'Спецификация',
				},
				{
					text:'СтатьяЗатрат',
				},
				{
					text:'СчетЗатрат',
				},
				{
					text:'СчетЗатратНУ',
				},
				{
					text:'ПодразделениеНЗП',
				},
				{
					text:'ПодразделениеОрганизацииНЗП',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:622px;height:24px;',
			items:
			[
				{
					text:'ЗаполнитьРаспределениеВозвратныхОтходов',
				},
				{
					text:'ПодменюЗаполнить',
				},
			]
		},
					]
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ПодразделениеОрганизации',
			style: 'position:absolute;left:424px;top:81px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Ответственный',
			style: 'position:absolute;left:96px;top:345px;width:548px;height:19px;',
		},
	]
});