Ext.define('Документы.ОтражениеЗарплатыВРеглУчете.ФормаДокумента',
	{
	extend: 'Ext.window.Window',
	height: 479,width: 659,
	iconCls: 'bogus',
	title: 'Отражение зарплаты в регламентированном учете',
	
	items:
	[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Номер',
			style: 'position:absolute;left:431px;top:33px;width:80px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Дата',
			style: 'position:absolute;left:531px;top:33px;width:120px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Организация',
			style: 'position:absolute;left:431px;top:57px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Ответственный',
			style: 'position:absolute;left:431px;top:81px;width:220px;height:19px;',
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:659px;height:25px;',
			items:
			[
				{
					text:'ДвиженияДокументаПоРегистрам',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'СтруктураПодчиненностиДокумента',
				},
				{
					text:'Разделитель8',
				},
				{
					text:'ОткрытьСвойства',
				},
				{
					text:'Разделитель7',
				},
				{
					text:'Очистить',
				},
				{
					text:'ОткрытьКатегории',
				},
				{
					text:'Подменю1',
				},
				{
					text:'ПроводкиДтКт',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ПроводкиДтКтНУ',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:454px;width:659px;height:25px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель1',
				},
			]
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:110px;width:643px;height:312px;',
			height: 312,width: 643,
			items:
			[
				{
					title:'Проводки',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:629px;height:24px;',
			items:
			[
				{
					text:'Действие12',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие14',
				},
				{
					text:'ГруппаРезервы',
				},
				{
					text:'Действие13',
				},
				{
					text:'ГруппаПустойСчетДт',
				},
				{
					text:'ГруппаПрочие',
				},
				{
					text:'ГруппаУдержания',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ГруппаВсеПроводки',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель',
				},
				{
					text:'СформироватьПроводки',
				},
				{
					text:'ГруппаНачисления',
				},
				{
					text:'ГруппаРБП',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие11',
				},
				{
					text:'ГруппаЕСНиПФР',
				},
				{
					text:'ГруппаНДФЛ',
				},
				{
					text:'ГруппаНСиПЗ',
				},
				{
					text:'ГруппаПособияФСС',
				},
				{
					text:'Действие10',
				},
				{
					text:'МенюГруппы',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие9',
				},
				{
					text:'ГруппаПустойСчетКт',
				},
				{
					text:'Действие17',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:629px;height:262px;',
			height: 262,width: 629,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'СчетДт',
				},
				{
					text:'ПодразделениеДт',
				},
				{
					text:'СубконтоДт1',
				},
				{
					text:'СубконтоДт2',
				},
				{
					text:'СубконтоДт3',
				},
				{
					text:'СпособРаспределенияЗатрат',
				},
				{
					text:'СчетКт',
				},
				{
					text:'ПодразделениеКт',
				},
				{
					text:'СубконтоКт1',
				},
				{
					text:'СубконтоКт2',
				},
				{
					text:'СубконтоКт3',
				},
				{
					text:'КодПоОКАТО',
				},
				{
					text:'КПП',
				},
				{
					text:'СчетДтНУ',
				},
				{
					text:'СубконтоДтНУ1',
				},
				{
					text:'СубконтоДтНУ2',
				},
				{
					text:'СубконтоДтНУ3',
				},
				{
					text:'СчетКтНУ',
				},
				{
					text:'СубконтоКтНУ1',
				},
				{
					text:'СубконтоКтНУ2',
				},
				{
					text:'СубконтоКтНУ3',
				},
				{
					text:'ОтражениеВУСН',
				},
				{
					text:'ВидНачисленияУдержанияИП',
				},
				{
					text:'ВидНачисленийОплатыТрудаПоСтатье255НК',
				},
				{
					text:'Сумма',
				},
				{
					text:'СуммаНУ',
				},
				{
					text:'СуммаПР',
				},
				{
					text:'СуммаВР',
				},
			]
		},
					]
				},
				{
					title:'ОсновныеНачисления',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:629px;height:24px;',
			items:
			[
				{
					text:'Действие12',
				},
				{
					text:'Действие14',
				},
				{
					text:'Действие11',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие10',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие15',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие17',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:629px;height:262px;',
			height: 262,width: 629,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияКонец',
				},
				{
					text:'СчетДт',
				},
				{
					text:'ПодразделениеДт',
				},
				{
					text:'СубконтоДт1',
				},
				{
					text:'СубконтоДт2',
				},
				{
					text:'СубконтоДт3',
				},
				{
					text:'СпособРаспределенияЗатрат',
				},
				{
					text:'СчетКт',
				},
				{
					text:'ПодразделениеКт',
				},
				{
					text:'СубконтоКт1',
				},
				{
					text:'СубконтоКт2',
				},
				{
					text:'СубконтоКт3',
				},
				{
					text:'СчетДтНУ',
				},
				{
					text:'СубконтоДтНУ1',
				},
				{
					text:'СубконтоДтНУ2',
				},
				{
					text:'СубконтоДтНУ3',
				},
				{
					text:'СчетКтНУ',
				},
				{
					text:'СубконтоКтНУ1',
				},
				{
					text:'СубконтоКтНУ2',
				},
				{
					text:'СубконтоКтНУ3',
				},
				{
					text:'ОтражениеВУСН',
				},
				{
					text:'ВидНачисленийОплатыТрудаПоСтатье255НК',
				},
				{
					text:'Результат',
				},
				{
					text:'СуммаНУ',
				},
				{
					text:'СуммаПР',
				},
				{
					text:'СуммаВР',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
			]
		},
					]
				},
				{
					title:'ДополнительныеНачисления',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:0px;width:629px;height:24px;',
			items:
			[
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие10',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие14',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие17',
				},
				{
					text:'Действие9',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:24px;width:629px;height:262px;',
			height: 262,width: 629,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'СчетДт',
				},
				{
					text:'ПодразделениеДт',
				},
				{
					text:'СубконтоДт1',
				},
				{
					text:'СубконтоДт2',
				},
				{
					text:'СубконтоДт3',
				},
				{
					text:'СпособРаспределенияЗатрат',
				},
				{
					text:'СчетКт',
				},
				{
					text:'ПодразделениеКт',
				},
				{
					text:'СубконтоКт1',
				},
				{
					text:'СубконтоКт2',
				},
				{
					text:'СубконтоКт3',
				},
				{
					text:'СчетДтНУ',
				},
				{
					text:'СубконтоДтНУ1',
				},
				{
					text:'СубконтоДтНУ2',
				},
				{
					text:'СубконтоДтНУ3',
				},
				{
					text:'СчетКтНУ',
				},
				{
					text:'СубконтоКтНУ1',
				},
				{
					text:'СубконтоКтНУ2',
				},
				{
					text:'СубконтоКтНУ3',
				},
				{
					text:'ОтражениеВУСН',
				},
				{
					text:'ВидНачисленийОплатыТрудаПоСтатье255НК',
				},
				{
					text:'Результат',
				},
				{
					text:'СуммаНУ',
				},
				{
					text:'СуммаПР',
				},
				{
					text:'СуммаВР',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
				{
					text:'ДатаНачисления',
				},
			]
		},
					]
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Комментарий',
			style: 'position:absolute;left:86px;top:427px;width:548px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ПредставлениеПериодаРегистрации',
			style: 'position:absolute;left:113px;top:33px;width:120px;height:19px;',
		},
		{
			xtype: 'button',
			name: 'КнопкаЗаполнить',
			text: 'Заполнить',
			style: 'position:absolute;left:8px;top:64px;width:120px;height:36px;',
		},
	]
});