Ext.define('Справочники.СтрокиФинансовогоРасчета.ФормаВводаФормулы',
	{
	extend: 'Ext.window.Window',
	height: 370,width: 433,
	iconCls: 'bogus',
	title: 'Ввод формулы',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:345px;width:433px;height:25px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:8px;top:93px;width:417px;height:52px;',
			items:
			[
				{
					text:'Кнопка9',
				},
				{
					text:'СтеретьСлева',
				},
				{
					text:'КнопкаТочка',
				},
				{
					text:'КнопкаУсловие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'КнопкаМакс',
				},
				{
					text:'Раздвинуть',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Кнопка1',
				},
				{
					text:'Кнопка0',
				},
				{
					text:'КнопкаМеньше',
				},
				{
					text:'Кнопка3',
				},
				{
					text:'КнопкаБольше',
				},
				{
					text:'Плюс',
				},
				{
					text:'Кнопка7',
				},
				{
					text:'Кнопка8',
				},
				{
					text:'Кнопка4',
				},
				{
					text:'Кнопка_',
				},
				{
					text:'Минус',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'КнопкаМин',
				},
				{
					text:'Кнопка5',
				},
				{
					text:'Умножить',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'СкобкаЗакрыть',
				},
				{
					text:'КодНаименование',
				},
				{
					text:'ШагВлево',
				},
				{
					text:'СкобкаОткрыть',
				},
				{
					text:'ШагВправо',
				},
				{
					text:'Кнопка2',
				},
				{
					text:'Удалить',
				},
				{
					text:'Кнопка6',
				},
				{
					text:'КнопкаРавно',
				},
				{
					text:'Разделить',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:145px;width:417px;height:192px;',
			height: 192,width: 417,
			columns:
			[
				{
					text:'Код',
				},
				{
					text:'СтрокаРасчета',
				},
			]
		},
	]
});