Ext.define('Обработки.АдминистрированиеПользователей.ФормаПрофилиПолномочийПользователей',
	{
	extend: 'Ext.window.Window',
	height: 443,width: 674,
	iconCls: 'bogus',
	title: 'Профили полномочий пользователей',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:674px;height:25px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'ДействиеНазначитьПрофильПользователям',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Подменю',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'ПодменюАдминистрированиеПользователей',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие4',
				},
				{
					text:'ДействиеСвойства',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие19',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель8',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие2',
				},
				{
					text:'ДействиеОбменВыгрузитьПрофили',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие9',
				},
				{
					text:'ДействиеПоказатьПользователейСТекущимПрофилем',
				},
				{
					text:'ДействиеСоздатьПрофили',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие3',
				},
				{
					text:'ДействиеСправка',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'ДействиеОбменЗагрузитьПрофили',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие8',
				},
				{
					text:'РазделительАдминистрирование',
				},
				{
					text:'Действие8',
				},
				{
					text:'ДействиеКатегории',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:246px;top:129px;width:420px;height:98px;',
			height: 98,width: 420,
			columns:
			[
				{
					text:'ПредставлениеРоли',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:232px;height:378px;',
			height: 378,width: 232,
			columns:
			[
				{
					text:'Наименование',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:246px;top:285px;width:420px;height:126px;',
			height: 126,width: 420,
			columns:
			[
				{
					text:'Право',
				},
				{
					text:'Значение',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:246px;top:258px;width:420px;height:24px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'ДействиеКопироватьПрава',
				},
				{
					text:'ДействиеУстановитьФлажки',
				},
				{
					text:'ДействиеСнятьФлажки',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:246px;top:105px;width:420px;height:24px;',
			items:
			[
				{
					text:'ДействиеИзменить',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:418px;width:674px;height:25px;',
			items:
			[
				{
					text:'ДействиеЗакрыть',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ДействиеОК',
				},
				{
					text:'ДействиеСохранитьПрофиль',
				},
			]
		},
	]
});