Ext.define('Справочники.ДоходыНДФЛ.ФормаВыбора',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:508px;height:320px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Коды доходов НДФЛ',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:32px;width:492px;height:280px;',
			height: 280,width: 492,
			columns:
			[
				{
					text:'',
					width:'32',
				},
				{
					text:'Код',
					width:'80',
				},
				{
					text:'Наименование',
					width:'220',
				},
				{
					text:'Ставка',
					width:'80',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:508px;height:25px;',
			items:
			[
				{
					text:'Действие5',
				},
				'-',
				'-',
				'-',
				{
					text:'Действие2',
				},
				{
					text:'Действие7',
				},
				'-',
				{
					text:'Действие9',
				},
				'-',
				{
					text:'Действие1',
				},
				{
					text:'',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие7',
				},
				{
					text:'',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие10',
				},
				'-',
				'-',
				'-',
				{
					text:'Действие6',
				},
				{
					text:'Действие6',
				},
				{
					text:'',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие2',
				},
				'-',
				{
					text:'Действие4',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие11',
				},
				'-',
				{
					text:'Действие3',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие5',
				},
			]
		},
	]
});