Ext.define('Справочники.Контрагенты.ФормаЭлемента',
	{
	extend: 'Ext.window.Window',
	height: 454,width: 560,
	iconCls: 'bogus',
	title: 'Контрагенты',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:560px;height:25px;',
			items:
			[
				{
					text:'ТелефонныйЗвонок',
				},
				{
					text:'НовыйЗаказПокупателя',
				},
				{
					text:'Прочее',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ЛичнаяВстреча',
				},
				{
					text:'ЭлектронноеПисьмо',
				},
				{
					text:'СписокСобытий',
				},
				{
					text:'Разделитель6',
				},
				{
					text:'ПочтовоеПисьмо',
				},
				{
					text:'Файлы',
				},
				{
					text:'Действие5',
				},
				{
					text:'Разделитель8',
				},
				{
					text:'Отчет',
				},
				{
					text:'Действие4',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ЗаказыПокупателей',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Отчеты',
				},
				{
					text:'Действие2',
				},
				{
					text:'Создать',
				},
				{
					text:'Создать',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Файлы',
				},
				{
					text:'НаписатьПисьмо',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ЭлектронноеПисьмо',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие',
				},
				{
					text:'ЭлектронныеПисьма',
				},
				{
					text:'ТелефонныйЗвонок',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действия',
				},
				{
					text:'Действие3',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Прочее',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие',
				},
				{
					text:'ЭлектронныеПисьмаПлюсКонтактныеЛица',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Действие3',
				},
				{
					text:'ПочтовоеПисьмо',
				},
				{
					text:'НовыйЗаказПокупателя',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель7',
				},
				{
					text:'НовыйЗаказПоставщику',
				},
				{
					text:'НовыйЗаказПоставщику',
				},
				{
					text:'Действие1',
				},
				{
					text:'Продажи',
				},
				{
					text:'ЗаказыПоставщикам',
				},
				{
					text:'Отчет',
				},
				{
					text:'ВедомостьВзаиморасчетов',
				},
				{
					text:'ЛичнаяВстреча',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:429px;width:560px;height:25px;',
			items:
			[
				{
					text:'Действие',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие1',
				},
			]
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:61px;width:544px;height:336px;',
			height: 336,width: 544,
			items:
			[
				{
					title:'Общие',
				},
				{
					title:'Контакты',
				},
				{
					title:'СчетаИДоговоры',
				},
				{
					title:'События',
				},
				{
					title:'Свойства',
				},
				{
					title:'Категории',
				},
				{
					title:'Прочее',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Код',
			style: 'position:absolute;left:472px;top:33px;width:80px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Наименование',
			style: 'position:absolute;left:94px;top:33px;width:338px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'КомментарийСтрокой',
			style: 'position:absolute;left:94px;top:402px;width:458px;height:19px;',
		},
	]
});