Ext.define('Отчеты.МониторЭффективности.НастройкаСтруктурыОтчета',
	{
	extend: 'Ext.window.Window',
	height: 321,width: 801,
	iconCls: 'bogus',
	title: 'Настройка структуры монитора',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:296px;width:801px;height:25px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'ДействиеСправка',
				},
				{
					text:'ДействиеОК',
				},
				{
					text:'ОсновныеДействияФормыЗакрыть',
				},
				{
					text:'Разделитель1',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:785px;height:222px;',
			height: 222,width: 785,
			columns:
			[
				{
					text:'Представление',
				},
				{
					text:'Тренд',
				},
				{
					text:'ИндикаторСостояния',
				},
				{
					text:'ТекущееЗначение',
				},
				{
					text:'ПредыдущееЗначение',
				},
				{
					text:'ИзменениеПроцент',
				},
				{
					text:'ИзменениеАбс',
				},
				{
					text:'ПланФакт',
				},
				{
					text:'ЗначениеПлан',
				},
				{
					text:'ПроцентВыполнения',
				},
				{
					text:'ОтклонениеПроцент',
				},
				{
					text:'ОтклонениеАбс',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:8px;top:8px;width:785px;height:24px;',
			items:
			[
				{
					text:'Действие6',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие',
				},
				{
					text:'ДействиеДобавитьГруппу',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'ДействиеПодбор',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ДействиеСнятьФлажки',
				},
				{
					text:'ДействиеУстановитьФлажки',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие5',
				},
			]
		},
	]
});