Ext.define('Справочники.ЗаявкиКандидатов.ФормаВыбора',
	{
	extend: 'Ext.window.Window',
	height: 400,width: 649,
	iconCls: 'bogus',
	title: 'Кандидаты',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:57px;width:633px;height:335px;',
			height: 335,width: 633,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'Важность',
				},
				{
					text:'Код',
				},
				{
					text:'Наименование',
				},
				{
					text:'Состояние',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'Организация',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Организация',
			style: 'position:absolute;left:341px;top:33px;width:300px;height:19px;',
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:649px;height:24px;',
			items:
			[
				{
					text:'Подменю1',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие7',
				},
				{
					text:'Перейти',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие5',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие5',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие8',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'Действие9',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ДействиеФормыВыбрать',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие4',
				},
				{
					text:'Подменю1',
				},
			]
		},
	]
});