Ext.define('Обработки.ПолучениеПочты.Форма',
	{
	extend: 'Ext.window.Window',
	height: 446,width: 636,
	iconCls: 'bogus',
	title: 'Получение почты',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:636px;height:25px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'ОткрытьСобытие',
				},
				{
					text:'ПоказатьПисьмо',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ОткрытьСобытие',
				},
				{
					text:'СнятьФлаги',
				},
				{
					text:'СнятьФлаги',
				},
				{
					text:'Настройка',
				},
				{
					text:'Обновить',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Действие',
				},
				{
					text:'ОткрытьЖурнал1',
				},
				{
					text:'УстановитьФлаги',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Обновить',
				},
				{
					text:'РедактироватьПисьмо',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие1',
				},
				{
					text:'УстановитьФлаги',
				},
				{
					text:'ОткрытьЖурнал',
				},
				{
					text:'Разделитель1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:421px;width:636px;height:25px;',
			items:
			[
				{
					text:'Выполнить',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:620px;height:380px;',
			height: 380,width: 620,
			columns:
			[
				{
					text:'Использование',
				},
				{
					text:'Вложения',
				},
				{
					text:'АдресОтправителя',
				},
				{
					text:'Отправитель',
				},
				{
					text:'Тема',
				},
			]
		},
	]
});