Ext.define('Документы.ЗаявлениеВФССНаДетейИнвалидов.ФормаВыбора',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:800px;height:500px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Заявления в ФСС о возмещении выплат родителям детей-инвалидов',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:784px;height:459px;',
			height: 459,width: 784,
			columns:
			[
				{
					text:'',
					width:'24',
				},
				{
					text:'Дата',
					width:'132',
				},
				{
					text:'Номер',
					width:'80',
				},
				{
					text:'Организация',
					width:'120',
				},
				{
					text:'Ответственный',
					width:'120',
				},
				{
					text:'Комментарий',
					width:'120',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:800px;height:25px;',
			items:
			[
				'-',
				{
					text:'',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие9',
				},
				'-',
				{
					text:'Действие8',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие6',
				},
				'-',
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
				'-',
				{
					text:'Действие3',
				},
				'-',
				{
					text:'Действие8',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие5',
				},
				'-',
				'-',
				{
					text:'Действие7',
				},
				{
					text:'Действие1',
				},
				'-',
				{
					text:'Действие',
				},
				{
					text:'',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие4',
				},
				'-',
				{
					text:'',
				},
				'-',
				{
					text:'Действие11',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие12',
				},
				'-',
				{
					text:'Действие6',
				},
				'-',
				{
					text:'Действие5',
				},
				{
					text:'Действия формы выбрать',
				},
				{
					text:'Действие2',
				},
				'-',
				{
					text:'Структура подчиненности документа',
				},
				{
					text:'Действие3',
				},
			]
		},
	]
});