Ext.define('Справочники.КурсыОбучения.ФормаСписка',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:679px;height:300px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Курсы обучения',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:156px;top:33px;width:515px;height:259px;',
			height: 259,width: 515,
			columns:
			[
				{
					text:'',
					width:'33',
				},
				{
					text:'Наименование',
					width:'350',
				},
				{
					text:'Объем',
					width:'55',
				},
				{
					text:'Затраты',
					width:'58',
				},
				{
					text:'Валюта',
					width:'55',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:142px;height:259px;',
			height: 259,width: 142,
			columns:
			[
				{
					text:'Наименование',
					width:'100',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:679px;height:25px;',
			items:
			[
				'-',
				{
					text:'Действие7',
				},
				{
					text:'Действие6',
				},
				'-',
				'-',
				{
					text:'Действие5',
				},
				{
					text:'Действие12',
				},
				{
					text:'',
				},
				'-',
				{
					text:'Действие',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие11',
				},
				{
					text:'Действие13',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие8',
				},
				'-',
				'-',
				{
					text:'Действие14',
				},
				'-',
				'-',
				{
					text:'',
				},
				{
					text:'Действие',
				},
				'-',
				{
					text:'Действие9',
				},
				'-',
				{
					text:'',
				},
				{
					text:'Действие1',
				},
				'-',
				{
					text:'Действие12',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие16',
				},
				{
					text:'Действие9',
				},
				{
					text:'Печать',
				},
				'-',
				{
					text:'Действие4',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие3',
				},
			]
		},
	]
});