Ext.define('Обработки.НастройкаПравДоступа.НастройкаПравДоступа',
	{
	extend: 'Ext.window.Window',
	height: 378,width: 854,
	iconCls: 'bogus',
	title: 'Настройка прав доступа',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:854px;height:25px;',
			items:
			[
				{
					text:'ДействиеЗаполнить',
				},
				{
					text:'ДействиеСправка',
				},
				{
					text:'ДействиеОтчетНастройкаПравДоступа',
				},
				{
					text:'РазделительЗаполнить',
				},
				{
					text:'НаследуемыеЗаписи',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ДействиеОтчетСведенияОГруппахПользователей',
				},
				{
					text:'ПодменюОтчеты',
				},
				{
					text:'Разделитель8',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:353px;width:854px;height:25px;',
			items:
			[
				{
					text:'Записать',
				},
				{
					text:'ОК',
				},
				{
					text:'Отмена',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель',
				},
			]
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:230px;top:33px;width:616px;height:312px;',
			height: 312,width: 616,
			items:
			[
				{
					title:'Контрагенты',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
				{
					text:'Чтение_3',
				},
				{
					text:'Изменение_3',
				},
				{
					text:'Чтение_2',
				},
				{
					text:'Изменение_2',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Подбор',
				},
				{
					text:'Действие',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
				{
					text:'УстановитьФлажки',
				},
			]
		},
					]
				},
				{
					title:'Организации',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Подбор',
				},
			]
		},
					]
				},
				{
					title:'Подразделения',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Подбор',
				},
				{
					text:'Действие1',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие3',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие2',
				},
			]
		},
					]
				},
				{
					title:'Проекты',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Разделитель2',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Подбор',
				},
			]
		},
					]
				},
				{
					title:'Склады',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие1',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие',
				},
			]
		},
					]
				},
				{
					title:'ФизическиеЛица',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
				{
					text:'Чтение_2',
				},
				{
					text:'Изменение_2',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие3',
				},
				{
					text:'Подбор',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие1',
				},
				{
					text:'СнятьФлажки',
				},
			]
		},
					]
				},
				{
					title:'ВнешниеОбработки',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
				{
					text:'Подбор',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие',
				},
			]
		},
					]
				},
				{
					title:'Заметки',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Подбор',
				},
			]
		},
					]
				},
				{
					title:'ПодразделенияОрганизаций',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Разделитель2',
				},
				{
					text:'Действие',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие3',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Разделитель',
				},
				{
					text:'СнятьФлажки',
				},
			]
		},
					]
				},
				{
					title:'ЗаявкиКандидатов',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
			]
		},
					]
				},
				{
					title:'Номенклатура',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:240px;',
			height: 240,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие',
				},
				{
					text:'Подбор',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие3',
				},
			]
		},
					]
				},
				{
					title:'Спецификации',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Подбор',
				},
				{
					text:'Разделитель',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие1',
				},
				{
					text:'УстановитьФлажки',
				},
				{
					text:'Действие',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:602px;height:224px;',
			height: 224,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Запись_1',
				},
			]
		},
					]
				},
				{
					title:'ЦеныНоменклатуры',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:31px;width:602px;height:223px;',
			height: 223,width: 602,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'ОбъектДоступа',
				},
				{
					text:'Пользователь',
				},
				{
					text:'ВладелецПравДоступа',
				},
				{
					text:'ВидНаследованияПравДоступаИерархическихСправочников',
				},
				{
					text:'ГруппаЦеныКомпании',
				},
				{
					text:'Чтение_1',
				},
				{
					text:'Изменение_1',
				},
				{
					text:'ГруппаЦеныКонтрагентов',
				},
				{
					text:'Чтение_2',
				},
				{
					text:'Изменение_2',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:602px;height:24px;',
			items:
			[
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие3',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие1',
				},
				{
					text:'СнятьФлажки',
				},
				{
					text:'УстановитьФлажки',
				},
			]
		},
					]
				},
				{
					title:'СтраницаСлужебная',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:215px;height:312px;',
			height: 312,width: 215,
			columns:
			[
				{
					text:'Наименование',
				},
			]
		},
	]
});