Ext.define('Отчеты.ПродажиПоПериодам.Форма',
	{
	extend: 'Ext.window.Window',
	height: 580,width: 900,
	iconCls: 'bogus',
	title: 'Продажи по периодам',
	
	items:
	[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:900px;height:25px;',
			items:
			[
				{
					text:'Разделитель1',
				},
				{
					text:'ВосстановитьНастройку',
				},
				{
					text:'ВосстановитьНастройку',
				},
				{
					text:'РазделительСправка',
				},
				{
					text:'СохранитьНастройку',
				},
				{
					text:'РазделительЗаполнить',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Подменю',
				},
				{
					text:'СохранитьНастройку',
				},
			]
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:33px;width:884px;height:539px;',
			height: 539,width: 884,
			items:
			[
				{
					title:'Товары',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:870px;height:483px;',
			height: 483,width: 870,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'Номенклатура',
				},
				{
					text:'Поле_01',
				},
				{
					text:'Поле_02',
				},
				{
					text:'Поле_03',
				},
				{
					text:'Поле_04',
				},
				{
					text:'Поле_05',
				},
				{
					text:'Поле_06',
				},
				{
					text:'Поле_07',
				},
				{
					text:'Поле_08',
				},
				{
					text:'Поле_09',
				},
				{
					text:'Поле_10',
				},
				{
					text:'Поле_11',
				},
				{
					text:'Поле_12',
				},
				{
					text:'Поле_13',
				},
				{
					text:'Поле_14',
				},
				{
					text:'Поле_15',
				},
				{
					text:'Поле_16',
				},
				{
					text:'Поле_17',
				},
				{
					text:'Поле_18',
				},
				{
					text:'Поле_19',
				},
				{
					text:'Поле_20',
				},
				{
					text:'Поле_21',
				},
				{
					text:'Поле_22',
				},
				{
					text:'Поле_23',
				},
				{
					text:'Поле_24',
				},
				{
					text:'Поле_25',
				},
				{
					text:'Поле_26',
				},
				{
					text:'Поле_27',
				},
				{
					text:'Поле_28',
				},
				{
					text:'Поле_29',
				},
				{
					text:'Поле_30',
				},
				{
					text:'Поле_31',
				},
				{
					text:'Поле_32',
				},
				{
					text:'Поле_33',
				},
				{
					text:'Поле_34',
				},
				{
					text:'Поле_35',
				},
				{
					text:'Поле_36',
				},
				{
					text:'Поле_37',
				},
				{
					text:'Поле_38',
				},
				{
					text:'Поле_39',
				},
				{
					text:'Поле_40',
				},
				{
					text:'Продажи_01',
				},
				{
					text:'ПродажиПроцент_01',
				},
				{
					text:'Продажи_02',
				},
				{
					text:'ПродажиПроцент_02',
				},
				{
					text:'Продажи_03',
				},
				{
					text:'ПродажиПроцент_03',
				},
				{
					text:'Продажи_04',
				},
				{
					text:'ПродажиПроцент_04',
				},
				{
					text:'Продажи_05',
				},
				{
					text:'ПродажиПроцент_05',
				},
				{
					text:'Продажи_06',
				},
				{
					text:'ПродажиПроцент_06',
				},
				{
					text:'Продажи_07',
				},
				{
					text:'ПродажиПроцент_07',
				},
				{
					text:'Продажи_08',
				},
				{
					text:'ПродажиПроцент_08',
				},
				{
					text:'Продажи_09',
				},
				{
					text:'ПродажиПроцент_09',
				},
				{
					text:'Продажи_10',
				},
				{
					text:'ПродажиПроцент_10',
				},
				{
					text:'Продажи_11',
				},
				{
					text:'ПродажиПроцент_11',
				},
				{
					text:'Продажи_12',
				},
				{
					text:'ПродажиПроцент_12',
				},
				{
					text:'Продажи_13',
				},
				{
					text:'ПродажиПроцент_13',
				},
				{
					text:'Продажи_14',
				},
				{
					text:'ПродажиПроцент_14',
				},
				{
					text:'Продажи_15',
				},
				{
					text:'ПродажиПроцент_15',
				},
				{
					text:'Продажи_16',
				},
				{
					text:'ПродажиПроцент_16',
				},
				{
					text:'Продажи_17',
				},
				{
					text:'ПродажиПроцент_17',
				},
				{
					text:'Продажи_18',
				},
				{
					text:'ПродажиПроцент_18',
				},
				{
					text:'Продажи_19',
				},
				{
					text:'ПродажиПроцент_19',
				},
				{
					text:'Продажи_20',
				},
				{
					text:'ПродажиПроцент_20',
				},
				{
					text:'Продажи_21',
				},
				{
					text:'ПродажиПроцент_21',
				},
				{
					text:'Продажи_22',
				},
				{
					text:'ПродажиПроцент_22',
				},
				{
					text:'Продажи_23',
				},
				{
					text:'ПродажиПроцент_23',
				},
				{
					text:'Продажи_24',
				},
				{
					text:'ПродажиПроцент_24',
				},
				{
					text:'Продажи_25',
				},
				{
					text:'ПродажиПроцент_25',
				},
				{
					text:'Продажи_26',
				},
				{
					text:'ПродажиПроцент_26',
				},
				{
					text:'Продажи_27',
				},
				{
					text:'ПродажиПроцент_27',
				},
				{
					text:'Продажи_28',
				},
				{
					text:'ПродажиПроцент_28',
				},
				{
					text:'Продажи_29',
				},
				{
					text:'ПродажиПроцент_29',
				},
				{
					text:'Продажи_30',
				},
				{
					text:'ПродажиПроцент_30',
				},
				{
					text:'Остатки_01',
				},
				{
					text:'Остатки_02',
				},
				{
					text:'Остатки_03',
				},
				{
					text:'Остатки_04',
				},
				{
					text:'Остатки_05',
				},
				{
					text:'Остатки_06',
				},
				{
					text:'Остатки_07',
				},
				{
					text:'Остатки_08',
				},
				{
					text:'Остатки_09',
				},
				{
					text:'Остатки_10',
				},
				{
					text:'ОстаткиИтог',
				},
				{
					text:'Цена_01',
				},
				{
					text:'Цена_02',
				},
				{
					text:'Цена_03',
				},
				{
					text:'Цена_04',
				},
				{
					text:'Цена_05',
				},
				{
					text:'Цена_06',
				},
				{
					text:'Цена_07',
				},
				{
					text:'Цена_08',
				},
				{
					text:'Цена_09',
				},
				{
					text:'Цена_10',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:870px;height:24px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'ДействиеОтключитьОтбор',
				},
				{
					text:'Действие11',
				},
				{
					text:'ДействиеУстановитьОтборИСортировкуСписка',
				},
				{
					text:'ДействиеЗафиксировать',
				},
				{
					text:'Действие9',
				},
				{
					text:'ДействиеИсторияОтборов',
				},
				{
					text:'ДействиеВывестиСписок',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие12',
				},
				{
					text:'Действие14',
				},
				{
					text:'ДействиеНастройкаСписка',
				},
				{
					text:'Действие10',
				},
				{
					text:'Действие13',
				},
				{
					text:'ДействиеОтборПоЗначениюВТекущейКолонке',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель2',
				},
			]
		},
					]
				},
				{
					title:'Настройки',
					items:
					[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'КоличествоПериодов',
			style: 'position:absolute;left:482px;top:27px;width:40px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ДатаФормирования',
			style: 'position:absolute;left:118px;top:27px;width:80px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'КоличествоРабочихДней',
			style: 'position:absolute;left:604px;top:27px;width:40px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'График',
			style: 'position:absolute;left:696px;top:27px;width:180px;height:19px;',
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:6px;top:75px;width:870px;height:437px;',
			height: 437,width: 870,
			items:
			[
				{
					title:'СтраницаПоля',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:438px;top:46px;width:424px;height:158px;',
			height: 158,width: 424,
			columns:
			[
				{
					text:'Склад',
				},
				{
					text:'Представление',
				},
				{
					text:'ВключатьВИтог',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:438px;top:22px;width:424px;height:24px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие5',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:438px;top:253px;width:424px;height:158px;',
			height: 158,width: 424,
			columns:
			[
				{
					text:'ТипЦен',
				},
				{
					text:'Представление',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:438px;top:229px;width:424px;height:24px;',
			items:
			[
				{
					text:'Действие8',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие4',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:46px;width:424px;height:365px;',
			height: 365,width: 424,
			columns:
			[
				{
					text:'Поле',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:22px;width:424px;height:24px;',
			items:
			[
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
			]
		},
					]
				},
				{
					title:'СтраницаОтборИСортировка',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:46px;width:424px;height:365px;',
			height: 365,width: 424,
			columns:
			[
				{
					text:'Использование',
				},
				{
					text:'Имя',
				},
				{
					text:'ВидСравнения',
				},
				{
					text:'Значение',
				},
				{
					text:'ЗначениеС',
				},
				{
					text:'ЗначениеПо',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:22px;width:424px;height:24px;',
			items:
			[
				{
					text:'Действие2',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие3',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:438px;top:46px;width:424px;height:365px;',
			height: 365,width: 424,
			columns:
			[
				{
					text:'Имя',
				},
				{
					text:'НаправлениеСортировки',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:438px;top:22px;width:424px;height:24px;',
			items:
			[
				{
					text:'Действие',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие3',
				},
			]
		},
					]
				},
			]
		},
					]
				},
			]
		},
	]
});