Ext.define('Документы.РасчетСтраховыхВзносов.ФормаДокумента',
	{
	extend: 'Ext.window.Window',
	height: 531,width: 782,
	iconCls: 'bogus',
	title: 'Начисление страховых взносов в ПФР, ФОМС и ФСС',
	
	items:
	[
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Номер',
			style: 'position:absolute;left:453px;top:33px;width:80px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Дата',
			style: 'position:absolute;left:553px;top:33px;width:120px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ПериодРегистрации',
			style: 'position:absolute;left:113px;top:59px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Организация',
			style: 'position:absolute;left:453px;top:59px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'ПодразделениеОрганизации',
			style: 'position:absolute;left:113px;top:33px;width:220px;height:19px;',
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Ответственный',
			style: 'position:absolute;left:453px;top:85px;width:220px;height:19px;',
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:782px;height:25px;',
			items:
			[
				{
					text:'ДвиженияДокументаПоРегистрам',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ОткрытьКатегории',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие',
				},
				{
					text:'ОткрытьСвойства',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'СтруктураПодчиненностиДокумента',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие6',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие3',
				},
				{
					text:'РедактироватьКодНомер',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие5',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие4',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель2',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:506px;width:782px;height:25px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Комментарий',
			style: 'position:absolute;left:96px;top:479px;width:678px;height:19px;',
		},
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:8px;top:131px;width:766px;height:341px;',
			height: 341,width: 766,
			items:
			[
				{
					title:'ИсчисленныеВзносы',
					items:
					[
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:752px;height:24px;',
			items:
			[
				{
					text:'Действие5',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие7',
				},
				{
					text:'РассчитатьВзносы',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие8',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие6',
				},
			]
		},
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:752px;height:285px;',
			height: 285,width: 752,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'ФСС',
				},
				{
					text:'ФССНесчастныеСлучаи',
				},
				{
					text:'ФФОМС',
				},
				{
					text:'ТФОМС',
				},
				{
					text:'ПФРСтраховая',
				},
				{
					text:'ПФРНакопительная',
				},
				{
					text:'ФССЕНВД',
				},
				{
					text:'ФФОМСЕНВД',
				},
				{
					text:'ТФОМСЕНВД',
				},
				{
					text:'ПФРСтраховаяЕНВД',
				},
				{
					text:'ПФРНакопительнаяЕНВД',
				},
				{
					text:'ПФРПоДополнительномуТарифу',
				},
				{
					text:'ПФРНаДоплатуКПенсииШахтерам',
				},
			]
		},
					]
				},
				{
					title:'ОсновныеНачисления',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:752px;height:285px;',
			height: 285,width: 752,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'ВидДохода',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияКонец',
				},
				{
					text:'Результат',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'ОблагаетсяПоДополнительномуТарифу',
				},
				{
					text:'ОблагаетсяВзносамиНаДоплатуКПенсииШахтерам',
				},
				{
					text:'ЯвляетсяДоходомФармацевта',
				},
				{
					text:'ЯвляетсяДоходомЧленаЭкипажаСуднаПодФлагомРФ',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:752px;height:24px;',
			items:
			[
				{
					text:'Подбор',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие3',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие5',
				},
			]
		},
					]
				},
				{
					title:'ДополнительныеНачисления',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:752px;height:285px;',
			height: 285,width: 752,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'ВидДохода',
				},
				{
					text:'Результат',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'ОблагаетсяПоДополнительномуТарифу',
				},
				{
					text:'ОблагаетсяВзносамиНаДоплатуКПенсииШахтерам',
				},
				{
					text:'ЯвляетсяДоходомФармацевта',
				},
				{
					text:'ЯвляетсяДоходомЧленаЭкипажаСуднаПодФлагомРФ',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:752px;height:24px;',
			items:
			[
				{
					text:'Действие1',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие4',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие7',
				},
			]
		},
					]
				},
				{
					title:'НеоблагаемыеСуммыДоходов',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:752px;height:285px;',
			height: 285,width: 752,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ФизЛицо',
				},
				{
					text:'ВидДохода',
				},
				{
					text:'Скидка',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:752px;height:24px;',
			items:
			[
				{
					text:'Разделитель1',
				},
				{
					text:'РассчитатьСкидку',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие5',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие4',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие1',
				},
			]
		},
					]
				},
				{
					title:'ПособияПоСоциальномуСтрахованию',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:752px;height:285px;',
			height: 285,width: 752,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ВидПособияСоциальногоСтрахования',
				},
				{
					text:'СпособФинансированияПособий',
				},
				{
					text:'ЗаголовокСтраховогоСлучая',
				},
				{
					text:'УчитыватьКакНовыйСтраховойСлучай',
				},
				{
					text:'ДатаСтраховогоСлучая',
				},
				{
					text:'ЗаголовокПериодаОплаты',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияКонец',
				},
				{
					text:'СуммаВсего',
				},
				{
					text:'ОплаченныеДни',
				},
				{
					text:'СуммаСверхНорм',
				},
				{
					text:'ВыплатаЗаСчетФедеральногоБюджета',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'ЯвляетсяДоходомФармацевта',
				},
				{
					text:'ОблагаетсяПоДополнительномуТарифу',
				},
				{
					text:'ОблагаетсяВзносамиНаДоплатуКПенсииШахтерам',
				},
				{
					text:'ЯвляетсяДоходомЧленаЭкипажаСуднаПодФлагомРФ',
				},
				{
					text:'ДокументОснование',
				},
				{
					text:'Сторно',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:752px;height:24px;',
			items:
			[
				{
					text:'Действие4',
				},
				{
					text:'Действие6',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие',
				},
				{
					text:'Подбор',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие2',
				},
			]
		},
					]
				},
				{
					title:'ПособияПоУходуЗаРебенкомДоПолутораЛет',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:6px;top:30px;width:752px;height:285px;',
			height: 285,width: 752,
			columns:
			[
				{
					text:'НомерСтроки',
				},
				{
					text:'ТабельныйНомерСтрока',
				},
				{
					text:'Сотрудник',
				},
				{
					text:'ПериодДействияНачало',
				},
				{
					text:'ПериодДействияКонец',
				},
				{
					text:'ПособиеПоУходуЗаПервымРебенком',
				},
				{
					text:'ПособиеПоУходуЗаПервымРебенкомСверхНорм',
				},
				{
					text:'ПособиеПоУходуЗаВторымРебенком',
				},
				{
					text:'ПособиеПоУходуЗаВторымРебенкомСверхНорм',
				},
				{
					text:'ВыплатаЗаСчетФедеральногоБюджета',
				},
				{
					text:'ВидРасчета',
				},
				{
					text:'ОблагаетсяЕНВД',
				},
				{
					text:'ОблагаетсяПоДополнительномуТарифу',
				},
				{
					text:'ОблагаетсяВзносамиНаДоплатуКПенсииШахтерам',
				},
				{
					text:'ЯвляетсяДоходомФармацевта',
				},
				{
					text:'ЯвляетсяДоходомЧленаЭкипажаСуднаПодФлагомРФ',
				},
				{
					text:'Сторно',
				},
				{
					text:'ДокументОснование',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:6px;top:6px;width:752px;height:24px;',
			items:
			[
				{
					text:'Действие3',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Подбор',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие7',
				},
			]
		},
					]
				},
			]
		},
		{
			xtype: 'button',
			name: 'КнопкаЗаполнить',
			text: 'Заполнить и рассчитать',
			style: 'position:absolute;left:8px;top:85px;width:193px;height:36px;',
		},
	]
});