Ext.define('Справочники.НормативныеДокументыСертификацииНоменклатуры.ФормаСписка',
	{
	extend: 'Ext.window.Window',
	style: 'position:absolute;width:360px;height:321px;',
	iconCls: 'bogus',
	minimizable: true,
	maximizable: true,
	title: 'Нормативные документы сертификации номенклатуры',
	
	items:
	[
		{
			xtype: 'grid',
			style: 'position:absolute;left:8px;top:33px;width:344px;height:280px;',
			height: 280,width: 344,
			columns:
			[
				{
					text:'',
					width:'32',
				},
				{
					text:'Код',
					width:'40',
				},
				{
					text:'Наименование',
					width:'220',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:0px;width:360px;height:25px;',
			items:
			[
				{
					text:'Действие6',
				},
				'-',
				'-',
				'-',
				{
					text:'Действие8',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие7',
				},
				{
					text:'Действие8',
				},
				{
					text:'Действие9',
				},
				'-',
				{
					text:'Действие2',
				},
				'-',
				{
					text:'Действие1',
				},
				{
					text:'Действие2',
				},
				{
					text:'Действие',
				},
				{
					text:'',
				},
				'-',
				{
					text:'',
				},
				'-',
				{
					text:'Действие5',
				},
				{
					text:'Действие3',
				},
				{
					text:'',
				},
				{
					text:'Действие4',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие7',
				},
				{
					text:'',
				},
				{
					text:'Действие10',
				},
				'-',
				{
					text:'Действие5',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие11',
				},
				'-',
				{
					text:'',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие1',
				},
			]
		},
	]
});