Ext.define('Обработки.УправлениеДаннымиРаботника.Форма',
	{
	extend: 'Ext.window.Window',
	height: 450,width: 780,
	iconCls: 'bogus',
	title: 'Иванова Анна Петровна',
	
	items:
	[
		{
			xtype: 'tabpanel',
			style: 'position:absolute;left:0px;top:51px;width:780px;height:399px;',
			height: 399,width: 780,
			items:
			[
				{
					title:'Основное',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:294px;top:312px;width:475px;height:76px;',
			height: 76,width: 475,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'Код',
				},
				{
					text:'Наименование',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:294px;top:287px;width:475px;height:25px;',
			items:
			[
				{
					text:'Действие13',
				},
				{
					text:'Действие14',
				},
				{
					text:'Действие2',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие8',
				},
				{
					text:'ВыбратьФизлицо',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие6',
				},
				{
					text:'Действие3',
				},
				{
					text:'Подменю1',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие1',
				},
				{
					text:'Действие9',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие7',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Действие15',
				},
				{
					text:'Действие3',
				},
				{
					text:'Действие1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'Подменю',
				},
				{
					text:'Действие2',
				},
			]
		},
					]
				},
				{
					title:'РасчетыЗарплата',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:294px;top:312px;width:475px;height:76px;',
			height: 76,width: 475,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'Вид документа',
				},
				{
					text:'Номер',
				},
				{
					text:'Дата',
				},
				{
					text:'Месяц',
				},
				{
					text:'Организация',
				},
				{
					text:'Комментарий',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:294px;top:287px;width:475px;height:25px;',
			items:
			[
				{
					text:'Действие',
				},
				{
					text:'ОплатаПоСреднемуЗаработку',
				},
				{
					text:'РегистрацияПростоевРаботниковОрганизаций',
				},
				{
					text:'Разделитель6',
				},
				{
					text:'РегистрацияРазовыхУдержанийРаботниковОрганизаций',
				},
				{
					text:'СдельныйНаряд',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель5',
				},
				{
					text:'РасчетПриУвольненииРаботникаОрганизаций',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель7',
				},
				{
					text:'ОплатаСверхурочныхЧасов',
				},
				{
					text:'НачислениеПоБольничномуЛисту',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие2',
				},
				{
					text:'НачислениеЕдиновременныхПособийЗаСчетФСС',
				},
				{
					text:'Разделитель4',
				},
				{
					text:'НачислениеОтпускаРаботникамОрганизаций',
				},
				{
					text:'ПремииРаботниковОрганизаций',
				},
				{
					text:'Разделитель3',
				},
				{
					text:'РегистрацияРазовыхНачисленийРаботниковОрганизаций',
				},
				{
					text:'НачислениеДивидендовОрганизаций',
				},
				{
					text:'ОплатаПраздничныхИВыходныхДнейОрганизаций',
				},
				{
					text:'НачислениеЗарплатыРаботникамОрганизаций',
				},
				{
					text:'Действие5',
				},
				{
					text:'НевыходыВОрганизациях',
				},
			]
		},
					]
				},
				{
					title:'ПлановыеДанные',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:294px;top:312px;width:475px;height:76px;',
			height: 76,width: 475,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'Вид документа',
				},
				{
					text:'Дата',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:294px;top:287px;width:475px;height:25px;',
			items:
			[
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ПриемНаРаботуВОрганизацию',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'ВводСведенийОПлановыхНачисленияхРаботниковОрганизаций',
				},
				{
					text:'ИсполнительныйЛист',
				},
				{
					text:'КадровоеПеремещениеОрганизаций',
				},
				{
					text:'Действие2',
				},
				{
					text:'УвольнениеИзОрганизаций',
				},
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ОтпускПоУходуЗаРебенком',
				},
				{
					text:'ВводСведенийОПлановыхУдержанияхРаботниковОрганизаций',
				},
				{
					text:'Действие5',
				},
			]
		},
					]
				},
				{
					title:'КадровыеДанные',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:294px;top:312px;width:475px;height:76px;',
			height: 76,width: 475,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'Вид документа',
				},
				{
					text:'Дата',
				},
				{
					text:'Организация',
				},
				{
					text:'Работники',
				},
				{
					text:'Ответственный',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:294px;top:287px;width:475px;height:25px;',
			items:
			[
				{
					text:'Разделитель',
				},
				{
					text:'КадровоеПеремещениеОрганизаций',
				},
				{
					text:'ЗаявлениеОбОбменеДубликатеСтраховогоСвидетельства',
				},
				{
					text:'ПриемНаРаботуВОрганизацию',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Разделитель',
				},
				{
					text:'СведенияОТрудовомСтажеЗастрахованногоЛицаСЗВК',
				},
				{
					text:'УвольнениеИзОрганизаций',
				},
				{
					text:'АнкетаЗастрахованногоЛица',
				},
				{
					text:'Действие',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие2',
				},
			]
		},
					]
				},
				{
					title:'Налоги',
					items:
					[
		{
			xtype: 'grid',
			style: 'position:absolute;left:294px;top:312px;width:475px;height:76px;',
			height: 76,width: 475,
			columns:
			[
				{
					text:'Картинка',
				},
				{
					text:'Вид документа',
				},
				{
					text:'Дата',
				},
				{
					text:'Колонка1',
				},
				{
					text:'Организация',
				},
				{
					text:'Комментарий',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:294px;top:287px;width:475px;height:25px;',
			items:
			[
				{
					text:'Разделитель1',
				},
				{
					text:'ОтражениеЗарплатыВРеглУчете',
				},
				{
					text:'Действие2',
				},
				{
					text:'РасчетЕСН',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Действие5',
				},
				{
					text:'Действие',
				},
				{
					text:'РасчетСтраховыхВзносов',
				},
				{
					text:'Разделитель',
				},
			]
		},
					]
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:0px;top:26px;width:780px;height:25px;',
			items:
			[
				{
					text:'РасчетыЗарплата',
				},
				{
					text:'Основное',
				},
				{
					text:'Разделитель2',
				},
				{
					text:'Разделитель1',
				},
				{
					text:'Налоги',
				},
				{
					text:'КадровыеДанные',
				},
				{
					text:'Разделитель',
				},
				{
					text:'ПлановыеДанные',
				},
				{
					text:'Разделитель3',
				},
			]
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:727px;top:2px;width:53px;height:24px;',
			items:
			[
				{
					text:'Действие',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Действие2',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'Физлицо',
			style: 'position:absolute;left:151px;top:4px;width:229px;height:19px;',
		},
		{
			xtype: 'toolbar',
			style: 'position:absolute;left:380px;top:2px;width:201px;height:24px;',
			items:
			[
				{
					text:'ДействиеВыбрать',
				},
				{
					text:'ДействиеОткрыть',
				},
				{
					text:'ДействиеНовый',
				},
				{
					text:'Разделитель',
				},
				{
					text:'Разделитель1',
				},
			]
		},
		{
			xtype: 'textfield',
			hideLabel: true,
			name: 'МесяцСтрока',
			style: 'position:absolute;left:4px;top:4px;width:136px;height:19px;',
		},
	]
});